In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("housing.csv")

In [4]:
data.drop(columns=['longitude', 'latitude'], inplace=True)

In [6]:
data.dropna(inplace=True)

In [18]:
data

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [20]:
data['ocean_proximity'].unique()

<StringArray>
['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND']
Length: 5, dtype: str

In [22]:
data = data.join(pd.get_dummies(data.ocean_proximity))

In [29]:
data

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,False,False,False,True,False
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,False,False,False,True,False
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,False,False,False,True,False
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,False,False,False,True,False
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,False,True,False,False,False
20636,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,False,True,False,False,False
20637,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,False,True,False,False,False
20638,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,False,True,False,False,False
20639,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,False,True,False,False,False

In [30]:
data['bedrooms_per_house'] = data['total_bedrooms'] / data['households']
data['rooms_per_house'] = data['total_rooms'] / data['households']
data['population_per_house'] = data['population'] / data['households']

In [31]:
data

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN,bedrooms_per_house,rooms_per_house,population_per_house
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,False,False,False,True,False,1.023810,6.984127,2.555556
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,False,False,False,True,False,0.971880,6.238137,2.109842
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,False,False,False,True,False,1.073446,8.288136,2.802260
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,False,False,False,True,False,1.073059,5.817352,2.547945
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,False,False,False,True,False,1.081081,6.281853,2.181467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,False,True,False,False,False,1.133333,5.045455,2.560606
20636,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,False,True,False,False,False,1.315789,6.114035,3.122807
20637,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,False,True,False,False,False,1.120092,5.205543,2.325635
20638,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,False,True,False,False,False,1.171920,5.329513,2.123209
20639,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,False,True,False,False,False,1.162264,5.254717,2.616981

In [33]:
upper_limit = data['bedrooms_per_house'].quantile(0.99)

data = data[data['bedrooms_per_house'] <= upper_limit]

In [37]:
# Cap rooms_per_house at 10 
data.loc[data['rooms_per_house'] > 10, 'rooms_per_house'] = 10

In [40]:
# Cap population_per_house at 10
data.loc[data['population_per_house'] > 10, 'population_per_house'] = 10

In [43]:
data_new = data

In [66]:
data_new.drop(columns = ['ocean_proximity'], inplace=True)

In [113]:
data_new.corr()['median_house_value'].sort_values(ascending=False)

median_house_value      1.000000
median_income           0.689270
rooms_per_house         0.333428
<1H OCEAN               0.255428
NEAR BAY                0.159411
NEAR OCEAN              0.138371
total_rooms             0.135320
housing_median_age      0.104642
households              0.061913
total_bedrooms          0.051950
ISLAND                  0.023548
population             -0.029265
bedrooms_per_house     -0.090181
population_per_house   -0.255049
INLAND                 -0.483777
Name: median_house_value, dtype: float64

In [67]:
data_new

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN,bedrooms_per_house,rooms_per_house,population_per_house
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False,1.023810,6.984127,2.555556
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False,0.971880,6.238137,2.109842
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False,1.073446,8.288136,2.802260
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False,1.073059,5.817352,2.547945
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False,1.081081,6.281853,2.181467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,False,True,False,False,False,1.133333,5.045455,2.560606
20636,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,False,True,False,False,False,1.315789,6.114035,3.122807
20637,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,False,True,False,False,False,1.120092,5.205543,2.325635
20638,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,False,True,False,False,False,1.171920,5.329513,2.123209
20639,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,False,True,False,False,False,1.162264,5.254717,2.616981

In [88]:
from sklearn.preprocessing import StandardScaler

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
from sklearn.linear_model import LinearRegression

In [91]:
from sklearn.pipeline import make_pipeline

In [92]:
from sklearn.compose import make_column_transformer

In [93]:
lr = LinearRegression()

In [94]:
scaler = StandardScaler()

In [95]:
model = make_pipeline(scaler, lr)

In [96]:
X = data_new.drop(columns = ['median_house_value'])

In [97]:
y = data_new['median_house_value']

In [98]:
X_train, X_test, y_train, y_test = train_test_split(train_data, test_data, test_size=0.2)

In [99]:
model.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [100]:
model.score(X_test, y_test)

0.6536583742158516

In [108]:
import pandas as pd

input = pd.DataFrame([{
    'housing_median_age': 52.0,
    'total_rooms': 1274.0,
    'total_bedrooms': 235.0,
    'population': 558.0,
    'households': 219.0,
    'median_income': 5.6431,

    # one-hot encoded ocean columns (True/False → use 1/0)
    '<1H OCEAN': 0,
    'INLAND': 0,
    'ISLAND': 0,
    'NEAR BAY': 1,
    'NEAR OCEAN': 0,

    # engineered features
    'bedrooms_per_house': 1.073059,
    'rooms_per_house': 5.817352,
    'population_per_house': 2.547945
}])

In [109]:
model.predict(input)

array([333858.58833609])

In [110]:
import pickle as pk

In [111]:
pk.dump(model,open('House_Price_Prediction_Model.pkl','wb'))

In [112]:
data_new.to_csv('cleaned_data.csv')